baseURL = 'https://voidash.github.io/blog/'
languageCode = 'en-us'
title = 'AshLogs'
content= "Welcome to my blog"
theme = "PaperMod"
headline= 'Serenity'

[permalinks]
tutorials = "/blog/blogger/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true

[minify]
  disableXML = true

[Params]
giscusTheme="preferred_color_scheme"
disableComments=false
